import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import "../../public/bootstrap/css/bootstrap.min.css";
import Providers from "../redux/Providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tshop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
      </head>
      <Providers>
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
          <script src="../../public/bootstrap/js/bootstrap.bundle.min.js"></script>
        </body>
      </Providers>
    </html>
  );
}
